// Code generated by protoc-gen-go.
// source: naminglib.proto
// DO NOT EDIT!

package bns

//import proto "github.com/golang/protobuf/proto"
import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// data struct request for local naming-service request
type LocalNamingRequest struct {
	ServiceName      *string `protobuf:"bytes,1,opt,name=service_name" json:"service_name,omitempty"`
	All              *bool   `protobuf:"varint,2,opt,name=all,def=1" json:"all,omitempty"`
	Pid              *int32  `protobuf:"varint,3,opt,name=pid,def=-1" json:"pid,omitempty"`
	Type             *int32  `protobuf:"varint,4,opt,name=type,def=0" json:"type,omitempty"`
	HostName         *string `protobuf:"bytes,5,opt,name=host_name" json:"host_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalNamingRequest) Reset()         { *m = LocalNamingRequest{} }
func (m *LocalNamingRequest) String() string { return proto.CompactTextString(m) }
func (*LocalNamingRequest) ProtoMessage()    {}

const Default_LocalNamingRequest_All bool = true
const Default_LocalNamingRequest_Pid int32 = -1
const Default_LocalNamingRequest_Type int32 = 0

func (m *LocalNamingRequest) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *LocalNamingRequest) GetAll() bool {
	if m != nil && m.All != nil {
		return *m.All
	}
	return Default_LocalNamingRequest_All
}

func (m *LocalNamingRequest) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_LocalNamingRequest_Pid
}

func (m *LocalNamingRequest) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_LocalNamingRequest_Type
}

func (m *LocalNamingRequest) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

// data struct response for local naming-service response
type LocalNamingResponse struct {
	ServiceName      *string         `protobuf:"bytes,1,opt,name=service_name" json:"service_name,omitempty"`
	InstanceInfo     []*InstanceInfo `protobuf:"bytes,2,rep,name=instance_info" json:"instance_info,omitempty"`
	Retcode          *int32          `protobuf:"varint,3,opt,name=retcode" json:"retcode,omitempty"`
	Stale            *bool           `protobuf:"varint,4,opt,name=stale,def=0" json:"stale,omitempty"`
	Threshold        *int32          `protobuf:"varint,5,opt,name=threshold,def=0" json:"threshold,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *LocalNamingResponse) Reset()         { *m = LocalNamingResponse{} }
func (m *LocalNamingResponse) String() string { return proto.CompactTextString(m) }
func (*LocalNamingResponse) ProtoMessage()    {}

const Default_LocalNamingResponse_Stale bool = false
const Default_LocalNamingResponse_Threshold int32 = 0

func (m *LocalNamingResponse) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *LocalNamingResponse) GetInstanceInfo() []*InstanceInfo {
	if m != nil {
		return m.InstanceInfo
	}
	return nil
}

func (m *LocalNamingResponse) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *LocalNamingResponse) GetStale() bool {
	if m != nil && m.Stale != nil {
		return *m.Stale
	}
	return Default_LocalNamingResponse_Stale
}

func (m *LocalNamingResponse) GetThreshold() int32 {
	if m != nil && m.Threshold != nil {
		return *m.Threshold
	}
	return Default_LocalNamingResponse_Threshold
}

// data struct request for local naming-auth-service request
type LocalNamingAuthRequest struct {
	ServiceName      *string `protobuf:"bytes,1,opt,name=service_name" json:"service_name,omitempty"`
	All              *bool   `protobuf:"varint,2,opt,name=all,def=1" json:"all,omitempty"`
	Pid              *int32  `protobuf:"varint,3,opt,name=pid,def=-1" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalNamingAuthRequest) Reset()         { *m = LocalNamingAuthRequest{} }
func (m *LocalNamingAuthRequest) String() string { return proto.CompactTextString(m) }
func (*LocalNamingAuthRequest) ProtoMessage()    {}

const Default_LocalNamingAuthRequest_All bool = true
const Default_LocalNamingAuthRequest_Pid int32 = -1

func (m *LocalNamingAuthRequest) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *LocalNamingAuthRequest) GetAll() bool {
	if m != nil && m.All != nil {
		return *m.All
	}
	return Default_LocalNamingAuthRequest_All
}

func (m *LocalNamingAuthRequest) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_LocalNamingAuthRequest_Pid
}

// data struct response for local naming-auth-service response
type LocalNamingAuthResponse struct {
	ServiceName      *string            `protobuf:"bytes,1,opt,name=service_name" json:"service_name,omitempty"`
	TrustedServices  []*ServiceHostList `protobuf:"bytes,2,rep,name=trusted_services" json:"trusted_services,omitempty"`
	Retcode          *int32             `protobuf:"varint,3,opt,name=retcode" json:"retcode,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *LocalNamingAuthResponse) Reset()         { *m = LocalNamingAuthResponse{} }
func (m *LocalNamingAuthResponse) String() string { return proto.CompactTextString(m) }
func (*LocalNamingAuthResponse) ProtoMessage()    {}

func (m *LocalNamingAuthResponse) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *LocalNamingAuthResponse) GetTrustedServices() []*ServiceHostList {
	if m != nil {
		return m.TrustedServices
	}
	return nil
}

func (m *LocalNamingAuthResponse) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

type LocalServiceConfRequest struct {
	ServiceName      *string `protobuf:"bytes,1,opt,name=service_name" json:"service_name,omitempty"`
	Pid              *int32  `protobuf:"varint,3,opt,name=pid,def=-1" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalServiceConfRequest) Reset()         { *m = LocalServiceConfRequest{} }
func (m *LocalServiceConfRequest) String() string { return proto.CompactTextString(m) }
func (*LocalServiceConfRequest) ProtoMessage()    {}

const Default_LocalServiceConfRequest_Pid int32 = -1

func (m *LocalServiceConfRequest) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *LocalServiceConfRequest) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_LocalServiceConfRequest_Pid
}

type LocalServiceConfResponse struct {
	ServiceInfo      *ServiceInfo `protobuf:"bytes,1,opt,name=service_info" json:"service_info,omitempty"`
	Retcode          *int32       `protobuf:"varint,2,opt,name=retcode" json:"retcode,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *LocalServiceConfResponse) Reset()         { *m = LocalServiceConfResponse{} }
func (m *LocalServiceConfResponse) String() string { return proto.CompactTextString(m) }
func (*LocalServiceConfResponse) ProtoMessage()    {}

func (m *LocalServiceConfResponse) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *LocalServiceConfResponse) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

// data struct request for local naming-service-list request
type LocalNamingListRequest struct {
	RequestList      []*LocalNamingRequest `protobuf:"bytes,1,rep,name=request_list" json:"request_list,omitempty"`
	Pid              *int32                `protobuf:"varint,3,opt,name=pid,def=-1" json:"pid,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *LocalNamingListRequest) Reset()         { *m = LocalNamingListRequest{} }
func (m *LocalNamingListRequest) String() string { return proto.CompactTextString(m) }
func (*LocalNamingListRequest) ProtoMessage()    {}

const Default_LocalNamingListRequest_Pid int32 = -1

func (m *LocalNamingListRequest) GetRequestList() []*LocalNamingRequest {
	if m != nil {
		return m.RequestList
	}
	return nil
}

func (m *LocalNamingListRequest) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_LocalNamingListRequest_Pid
}

// data struct response for local naming-service-list response
type LocalNamingListResponse struct {
	NamingList       []*LocalNamingResponse `protobuf:"bytes,1,rep,name=naming_list" json:"naming_list,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *LocalNamingListResponse) Reset()         { *m = LocalNamingListResponse{} }
func (m *LocalNamingListResponse) String() string { return proto.CompactTextString(m) }
func (*LocalNamingListResponse) ProtoMessage()    {}

func (m *LocalNamingListResponse) GetNamingList() []*LocalNamingResponse {
	if m != nil {
		return m.NamingList
	}
	return nil
}

// data struct request for local naming-auth-service-list request
type LocalNamingAuthListRequest struct {
	RequestList      []*LocalNamingAuthRequest `protobuf:"bytes,1,rep,name=request_list" json:"request_list,omitempty"`
	Pid              *int32                    `protobuf:"varint,3,opt,name=pid,def=-1" json:"pid,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *LocalNamingAuthListRequest) Reset()         { *m = LocalNamingAuthListRequest{} }
func (m *LocalNamingAuthListRequest) String() string { return proto.CompactTextString(m) }
func (*LocalNamingAuthListRequest) ProtoMessage()    {}

const Default_LocalNamingAuthListRequest_Pid int32 = -1

func (m *LocalNamingAuthListRequest) GetRequestList() []*LocalNamingAuthRequest {
	if m != nil {
		return m.RequestList
	}
	return nil
}

func (m *LocalNamingAuthListRequest) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_LocalNamingAuthListRequest_Pid
}

// data struct response for local naming-auth-service-list response
type LocalNamingAuthListResponse struct {
	NamingAuthList   []*LocalNamingAuthResponse `protobuf:"bytes,1,rep,name=naming_auth_list" json:"naming_auth_list,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *LocalNamingAuthListResponse) Reset()         { *m = LocalNamingAuthListResponse{} }
func (m *LocalNamingAuthListResponse) String() string { return proto.CompactTextString(m) }
func (*LocalNamingAuthListResponse) ProtoMessage()    {}

func (m *LocalNamingAuthListResponse) GetNamingAuthList() []*LocalNamingAuthResponse {
	if m != nil {
		return m.NamingAuthList
	}
	return nil
}

func init() {
}
